apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-body-size: 4096M
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 8000
    - host: files.localhost
      http:
        paths:
          - backend:
              serviceName: minio-host
              servicePort: 9000
    - host: "*.web.localhost"
      http:
        paths:
          - backend:
              serviceName: web-proxy
              servicePort: 8001
---
apiVersion: v1
kind: Secret
metadata:
  name: debug-auth
type: Opaque
data:
  auth: ZGVidWc6JGFwcjEkaVkwUC90VGckZklPcWpIVmdaRThwQVlIb0ptLmlmMQo= # debug:debug
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-debug
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: debug-auth
    nginx.ingress.kubernetes.io/auth-realm: "Restricted"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /data
            backend:
              serviceName: web
              servicePort: 8000
