apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-web
spec:
  backend:
    serviceName: web
    servicePort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-minio
spec:
  backend:
    serviceName: minio-host
    servicePort: 9000
