apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-body-size: 4096M
spec:
  rules:
    - host: server.reprozip.org
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 8000
    - host: files.server.reprozip.org
      http:
        paths:
          - backend:
              serviceName: minio-host
              servicePort: 9000
    - host: "*.web.server.reprozip.org"
      http:
        paths:
          - backend:
              serviceName: web-proxy
              servicePort: 8001
