---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  labels:
    type: local
    app: minio
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/reproserver/prod/minio"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: "minio/minio:RELEASE.2017-04-29T00-40-27Z"
        args: ["server", "/export"]
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: reproserver-secret
              key: s3_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: reproserver-secret
              key: s3_secret
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /export
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: 9000
