---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: reproserver-secret
data:
  # Those values need to be encoded in base64
  postgres_user: cmVwcm9zZXJ2ZXJkYg== # "reproserverdb"
  # Fill those in with secret values
  postgres_password: aGFja21l # "hackme"
  s3_key: czNfYWNjZXNzX2tleQ== # "s3_access_key"
  s3_secret: czNfc2VjcmV0X2tleQ== # "s3_secret_key"
  connection_token: c2VjcmV0LXRva2Vu # "secret-token"
  zenodo_token: eHh4 # "xxx"
---
apiVersion: v1
kind: Secret
metadata:
  name: debug-auth
type: Opaque
data:
  auth: ZGVidWc6JGFwcjEkaVkwUC90VGckZklPcWpIVmdaRThwQVlIb0ptLmlmMQo= # debug:debug
